name: CI/CD Pipeline - TD4

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§¾ Checkout du code
        uses: actions/checkout@v4

      - name: ğŸ” Connexion Ã  Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ğŸ› ï¸ Build de l'image Docker
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/td4_java_app:latest .

      - name: ğŸ§ª Test du conteneur
        run: |
          docker run --name td4-test -d ${{ secrets.DOCKERHUB_USERNAME }}/td4_java_app:latest
          sleep 10
          docker logs td4-test
          docker rm -f td4-test

      - name: ğŸš€ Push de l'image sur Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/td4_java_app:latest